sudo: required
services:
  - docker

before_install:
  - docker build -t anhadgill23/docker_playground -f Dockerfile.dev .

script:
  - docker run -e CI=true anhadgill23/docker_playground npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-848061902760'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
